// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.computerlyrik.spring.securityobjects;

import de.computerlyrik.spring.securityobjects.UserDetailsSO;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect UserDetailsSO_Roo_Configurable {
    
    declare @type: UserDetailsSO: @Configurable;
    
}
